import {chromium,devices} from 'playwright';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const output=process.env.TEST_OUTPUT||'test-results';fs.mkdirSync(output,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.glb':'model/gltf-binary','.json':'application/json'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/kleines-schaeferrad\//,'');if(p.endsWith('/'))p+='index.html';const file=path.resolve('dist',p);if(!file.startsWith(path.resolve('dist')+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end('not found')}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res)});
await new Promise(r=>server.listen(4321,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.KS_CHROMIUM_PATH||undefined,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const results={date:new Date().toISOString(),type:'automated-simulated-field-test',physical_users:0,real_iphone_test:false,checks:[],errors:[]};
const url='http://127.0.0.1:4321/kleines-schaeferrad/werkstatt/';
try{
 for(const profile of [{name:'desktop',viewport:{width:1440,height:1000}},{name:'320px',viewport:{width:320,height:740}},{name:'iphone-17-pro-emulation',...devices['iPhone 17 Pro']},{name:'text-200pct',viewport:{width:1280,height:1000},textZoom:true}]){
  const {name,textZoom,...opts}=profile;const ctx=await browser.newContext(opts);const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push('console: '+m.text())});page.on('requestfailed',req=>errors.push('request: '+req.url()+' '+(req.failure()?.errorText||'')));await page.goto(url);try{await page.waitForFunction(()=>document.querySelector('#storage-status')?.textContent.includes('Lokal gesichert'),null,{timeout:60000});await page.waitForSelector('#canvas-host canvas',{timeout:60000})}catch(err){const diagnostic=await page.evaluate(()=>({storage:document.querySelector('#storage-status')?.textContent,render:document.querySelector('#render-status')?.textContent,canvas:!!document.querySelector('#canvas-host canvas'),readyState:document.readyState,scriptCount:document.scripts.length}));results.errors.push({profile:name,diagnostic,errors});await page.screenshot({path:path.join(output,`${name}-startup-failure.png`),fullPage:true});throw err}assert.match(await page.locator('#render-status').innerText(),/Ziehen:/);
  if(textZoom)await page.addStyleTag({content:':root{font-size:32px!important}'});
  assert.equal(await page.locator('#orbit').getAttribute('aria-pressed'),'true');
  const overflow=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));assert.ok(overflow.document<=overflow.viewport+1,`${name}: horizontal overflow ${JSON.stringify(overflow)}`);
  const small=await page.locator('.view-buttons button:visible,.model-controls button:visible,#reset:visible,#capture-actions button:visible,#part-list button:visible').evaluateAll(nodes=>nodes.filter(n=>{const r=n.getBoundingClientRect();return r.width<44||r.height<44}).map(n=>n.textContent));assert.deepEqual(small,[],`${name}: small frequent targets`);
  const start=Date.now();await page.locator('#part-search').fill('Kumpf');await page.locator('[data-part="COMP-KUEMPFE"]').click();assert.match(await page.locator('#selection h3').innerText(),/Kümpfe|Schöpfgefäße/);results.checks.push({profile:name,task:'find Kumpf',seconds:(Date.now()-start)/1000,help:'automated selectors; not human timing',passed:true});
  for(const mode of ['welle','kranz','kumpf'])await page.locator('#scene-mode').selectOption(mode);await page.locator('.technical-settings').evaluate(el=>el.open=true);await page.locator('#variant').click();assert.match(await page.locator('#variant').innerText(),/22 mm/);await page.locator('#explode').click();await page.locator('#cut').click();await page.locator('#reset').click();assert.equal(await page.locator('#orbit').getAttribute('aria-pressed'),'true');assert.match(await page.locator('#view-label').innerText(),/Gesamtanlage/i);
  await page.locator('.capture-shell').evaluate(el=>el.open=true);await page.locator('[data-kind="measurement"]').click();await page.locator('[name="feature"]').fill('SIMULATION – Daubendicke, kein reales Feldmaß');await page.locator('[name="value"]').fill('24');await page.locator('[name="endpoint_a"]').fill('TEST Innenfläche');await page.locator('[name="endpoint_b"]').fill('TEST Außenfläche');await page.locator('[name="tool"]').fill('SIMULATION Schieblehre');await page.locator('[name="uncertainty"]').fill('1');await page.locator('#step-next').click();await page.locator('[name="person"]').fill('AUTOMATISIERTER TEST');await page.locator('[name="event_id"]').fill('EVT-SIM-001');
  await page.locator('#media-input').setInputFiles({name:'simulation.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});await page.waitForFunction(()=>document.querySelector('#media-status').textContent.includes('Originalbytes'));
  await page.reload();await page.waitForFunction(()=>document.querySelector('#draft-status').textContent.includes('gesichert'));await page.locator('.capture-shell').evaluate(el=>el.open=true);assert.equal(await page.locator('[name="person"]').inputValue(),'AUTOMATISIERTER TEST');assert.equal(await page.locator('[name="feature"]').inputValue(),'SIMULATION – Daubendicke, kein reales Feldmaß');assert.match(await page.locator('#step-indicator').innerText(),/Schritt 2/);assert.equal(await page.locator('#media-list img').count(),1);
  await page.locator('#step-next').click();await page.locator('[name="claim_id"]').selectOption('CLAIM-0040');await page.locator('[name="effect"]').selectOption('supports');assert.match(await page.locator('#review').innerText(),/bestätigt die ausgewählte Aussage/);await page.locator('#save-record').click();await page.waitForFunction(()=>document.querySelector('#record-count').textContent==='1');assert.match(await page.locator('#selection').innerText(),/1 eigene Einträge/);
  const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;const exportPath=path.join(output,`${name}-capture.json`);await download.saveAs(exportPath);const capture=JSON.parse(fs.readFileSync(exportPath));assert.equal(capture.records.length,1);assert.equal(capture.records[0].media.length,1);assert.match(capture.records[0].media[0].data_url,/^data:image\/png;base64,/);assert.equal(capture.records[0].review_status,'unreviewed-local');
  await page.locator('#import').setInputFiles(exportPath);await page.waitForFunction(()=>document.querySelector('#storage-status').textContent.includes('nach Import'));assert.equal(await page.locator('#record-count').innerText(),'1');
  const ctx2=await browser.newContext(opts),other=await ctx2.newPage();await other.goto(url);await other.waitForFunction(()=>document.querySelector('#storage-status').textContent.includes('Lokal gesichert'));await other.locator('#import').setInputFiles(exportPath);await other.waitForFunction(()=>document.querySelector('#record-count').textContent==='1');await ctx2.close();
  await page.locator('#layer-scan').check();await page.waitForFunction(()=>document.querySelector('#scan-status').textContent.includes('Punktewolke'),{timeout:30000});assert.match(await page.locator('#scan-status').innerText(),/75\.619 Punkte/);await page.locator('#layer-scan').uncheck();
  await page.locator('#part-search').fill('');await page.locator('#workbench').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,`${name}.png`),fullPage:true});assert.deepEqual(errors,[]);results.checks.push({profile:name,task:'standard views, A/B, explode, cut, reset, measurement + photo, interrupted draft resume, capture review/update, lossless export/import, scan workspace, 44px targets, no page overflow',passed:true});await ctx.close();
 }
 results.status='passed';
}catch(e){results.status='failed';results.errors.push(e.stack);throw e}finally{fs.writeFileSync(path.join(output,'field-test-results.json'),JSON.stringify(results,null,2));await browser.close();server.close();}
