// Independent observation only. All typed/uploaded data is explicitly synthetic.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.UX_PLAYWRIGHT?pathToFileURL(process.env.UX_PLAYWRIGHT).href:'playwright');
const out=process.env.UX_OUTPUT||'test-results/ux-recovery';fs.mkdirSync(out,{recursive:true});
const base='https://jdistlr.github.io/kleines-schaeferrad/';
const report={started:new Date().toISOString(),base,scope:'Chromium emulation; no physical iPhone/Safari, printer or field approval',profiles:[],journeys:[],errors:[]};
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const b=await chromium.launch({headless:true,proxy:process.env.HTTPS_PROXY?{server:process.env.HTTPS_PROXY}:undefined,executablePath:process.env.KS_CHROMIUM_PATH||undefined,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});report.browser=b.version();
async function capture(p,name){await p.screenshot({path:`${out}/${name}.png`,fullPage:true});fs.writeFileSync(`${out}/${name}.txt`,await p.locator('body').innerText());return name+'.png'}
async function metrics(p){return p.evaluate(()=>({viewport:{width:innerWidth,height:innerHeight},scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,rootFont:getComputedStyle(document.documentElement).fontSize,overflow:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.right>innerWidth+1||r.left<-1)}).slice(0,20).map(e=>({tag:e.tagName,id:e.id,class:e.className})),targets:[...document.querySelectorAll('button,a,input,select,summary')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&getComputedStyle(e).visibility!=='hidden'}).map(e=>{const r=e.getBoundingClientRect();return {id:e.id,text:(e.innerText||e.getAttribute('aria-label')||e.type||'').slice(0,70),w:r.width,h:r.height}}).filter(r=>r.w<44||r.h<44),canvases:document.querySelectorAll('canvas').length,render:document.querySelector('#render-status')?.textContent}));}
async function ready(p,route){await p.goto(base+route,{waitUntil:'networkidle',timeout:90000});if(route==='feld/')await p.waitForFunction(()=>document.querySelector('#field-storage')?.textContent!=='Speicher wird geöffnet …');if(route==='werkstatt/')await p.waitForFunction(()=>document.querySelector('#render-status')?.textContent!=='3D wird geladen …');}
async function journey(name,fn){try{const details=await fn();report.journeys.push({name,executed:true,...details});}catch(e){report.journeys.push({name,executed:false,error:e.stack});}fs.writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));}
try{
 const res=await fetch(base+'offline-manifest.json');report.deployment=await res.json();
 for(const profile of [{name:'desktop',width:1440,height:1000},{name:'tablet',width:768,height:1024},{name:'phone390',width:390,height:844},{name:'phone320',width:320,height:740},{name:'text200',width:1280,height:1000,text200:true},{name:'reduced-motion',width:1440,height:1000,reducedMotion:'reduce'},{name:'dark',width:390,height:844,colorScheme:'dark'}]){
  const ctx=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:profile.width,height:profile.height},reducedMotion:profile.reducedMotion||'no-preference',colorScheme:profile.colorScheme||'light'});const p=await ctx.newPage();p.setDefaultTimeout(15000);const r={...profile,routes:[],errors:[]};p.on('pageerror',e=>r.errors.push(e.message));
  for(const route of ['','werkstatt/','feld/']){try{await ready(p,route);if(profile.text200){ // exact per-element text enlargement; no page zoom or geometry mutation
    await p.evaluate(()=>{const els=[...document.querySelectorAll('body,body *')];const sizes=els.map(e=>parseFloat(getComputedStyle(e).fontSize));els.forEach((e,i)=>e.style.setProperty('font-size',sizes[i]*2+'px','important'));});}
   const name=`${profile.name}-${route.replace('/','')||'story'}`;r.routes.push({route,screenshot:await capture(p,name),metrics:await metrics(p)});
   if(profile.name==='reduced-motion'&&route==='werkstatt/'){await p.locator('#scene-mode').selectOption('betrieb');const c=p.locator('#canvas-host canvas');if(await c.count()){const first=await c.screenshot();await p.waitForTimeout(700);const second=await c.screenshot();r.reducedMotion={media:await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),status:await p.locator('#operation-status').innerText(),canvasPixelsChanged:hash(first)!==hash(second),note:'Pixel change alone may include camera transition; inspect tick source and operation status before assigning severity'};fs.writeFileSync(`${out}/reduced-motion-frame-a.png`,first);fs.writeFileSync(`${out}/reduced-motion-frame-b.png`,second);}}
  }catch(e){r.routes.push({route,error:e.stack})}}
  report.profiles.push(r);await ctx.close();fs.writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));
 }
 const ctx=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000},acceptDownloads:true});const p=await ctx.newPage();p.setDefaultTimeout(20000);
 await journey('discover model, Kumpf sources, candidate and return',async()=>{await ready(p,'');await p.getByRole('link',{name:'Werkstattmodell',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#render-status')?.textContent!=='3D wird geladen …');await p.locator('#scene-mode').selectOption('kumpf');await p.locator('#part-search').fill('Kumpf');await p.locator('[data-part="COMP-KUEMPFE"]').click();await p.locator('#selection summary').filter({hasText:'Beobachtung und Rekonstruktion'}).click();const before=await p.locator('#selection').innerText();const links=await p.locator('#selection a[target="_blank"]').evaluateAll(es=>es.map(e=>({href:e.href,text:e.innerText})));await capture(p,'journey-kumpf');await p.locator('#model-mode').selectOption('truth');await capture(p,'journey-kumpf-truth');await p.locator('#model-mode').selectOption('brute');await p.locator('.technical-settings summary').first().click();await p.locator('#fastener-variant').selectOption('B');await capture(p,'journey-candidate-b');const source=links[0];let sourceStatus=null;if(source){const popPromise=p.waitForEvent('popup');await p.locator('#selection a[target="_blank"]').first().click();const pop=await popPromise;await pop.waitForLoadState();sourceStatus={url:pop.url(),body:await pop.locator('body').innerText()};await pop.close();}return {selection:before,links,sourceStatus,render:await p.locator('#render-status').innerText()};});
 await journey('urgent water capture, task index and navigation',async()=>{await ready(p,'feld/');await p.getByRole('link',{name:'Zur Wasseraufnahme',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#task-title')?.textContent.includes('Wasser'));await capture(p,'journey-water');const title=await p.locator('#task-title').innerText();await p.locator('[data-field="person"]').fill('UX AUDIT SIMULATION');await p.locator('#field-next').click();await p.locator('#field-next').click();await p.locator('#field-next').click();await p.locator('[data-field="unknown"]').check();await p.locator('[data-field="reason"]').fill('SIMULATION: keine reale Wasseraufnahme');await p.locator('#field-next').click();await p.locator('#field-next').click();await capture(p,'journey-after-water');return {waterTitle:title,nextTitle:await p.locator('#task-title').innerText(),url:p.url()};});
 await journey('two measurements and reload, original photo metadata, export/import',async()=>{await ready(p,'feld/');await p.locator('#open-index').click();await p.locator('[data-task="1"]').click();await p.locator('[data-field="person"]').fill('UX AUDIT SIMULATION');await p.locator('#field-next').click();const image=fs.readFileSync('evidence/raw/IMG_6858.jpeg');await p.locator('#field-photos').setInputFiles({name:'SIMULATION-original-reference.jpeg',mimeType:'image/jpeg',buffer:image});await p.waitForFunction(()=>document.querySelectorAll('.media-line').length===1&&!document.querySelector('#field-next').disabled);await p.locator('#field-next').click();await p.locator('[data-field="measurement.value"]').fill('123');await p.locator('[data-field="measurement.a"]').fill('SIMULATION DATUM A');await p.locator('[data-field="measurement.b"]').fill('SIMULATION DATUM B');await p.locator('[data-field="measurement.tool"]').fill('SIMULATION ruler');await p.locator('[data-field="measurement.uncertainty"]').fill('1');const measurementFields=await p.locator('[data-field^="measurement."]').count();await capture(p,'journey-single-measurement');await p.locator('[data-field="measurement.value"]').fill('456');await p.reload();await p.waitForSelector('[data-field="measurement.value"]');const resumed=await p.locator('[data-field="measurement.value"]').inputValue();await p.locator('#open-backup').click();const dlPromise=p.waitForEvent('download');await p.locator('#field-export').click();const dl=await dlPromise;const exportFile=`${out}/SIMULATION-export.json`;await dl.saveAs(exportFile);const data=JSON.parse(fs.readFileSync(exportFile));const media=data.media.map(m=>({name:m.name,bytes:m.bytes,sha256:m.sha256,actualHash:hash(Buffer.from(m.base64,'base64'))}));const c2=await b.newContext({ignoreHTTPSErrors:true,acceptDownloads:true});const p2=await c2.newPage();await ready(p2,'feld/');await p2.locator('#open-backup').click();await p2.locator('#field-import').setInputFiles(exportFile);await p2.waitForFunction(()=>document.querySelector('#backup-status').textContent.includes('Prüfsummen bestätigt'));const restore=await p2.locator('#backup-status').innerText();await p2.locator('#close-backup').click();await capture(p2,'journey-import-restored');await p2.reload();await p2.waitForSelector('[data-field="measurement.value"]');const restored=await p2.locator('[data-field="measurement.value"]').inputValue(); // conflicting import must not overwrite
 data.session.responses[Object.keys(data.session.responses).find(id=>data.session.responses[id].measurement?.value==='456')].measurement.value='999';const conflict=`${out}/SIMULATION-conflict.json`;fs.writeFileSync(conflict,JSON.stringify(data));await p2.locator('#open-backup').click();await p2.locator('#field-import').setInputFiles(conflict);await p2.waitForFunction(()=>document.querySelector('#field-error').textContent.includes('Abweichender'));const conflictMessage=await p2.locator('#field-error').innerText();await capture(p2,'journey-import-conflict');await c2.close();fs.unlinkSync(exportFile);fs.unlinkSync(conflict);return {measurementFields,resumed,restored,media,originalHash:hash(image),restore,conflictMessage,session:data.session,note:'First value 123 intentionally overwritten with 456 to observe missing second-measurement support; all values synthetic'};});
 await journey('offline readiness, reload, local data recovery, export',async()=>{await ready(p,'feld/');await p.waitForFunction(()=>document.querySelector('#offline-status').textContent.includes('Offline bereit'),null,{timeout:150000});const status=await p.locator('#offline-status').innerText();await ctx.setOffline(true);await p.reload({waitUntil:'networkidle'});await p.waitForSelector('[data-field="measurement.value"]');const value=await p.locator('[data-field="measurement.value"]').inputValue();await capture(p,'journey-offline-resume');await p.locator('#open-backup').click();const d=p.waitForEvent('download');await p.locator('#field-export').click();const dl=await d;const f=`${out}/SIMULATION-offline-export.json`;await dl.saveAs(f);const x=JSON.parse(fs.readFileSync(f));const result={status,value,mediaCount:x.media.length,offline:true};fs.unlinkSync(f);await ctx.setOffline(false);return result;});
 await journey('keyboard, long labels, partner provenance',async()=>{await ready(p,'feld/');await p.locator('#open-register').click();for(const [key,value] of Object.entries({id:'KS-KUM-999',local_name:'SIMULATION sehr lange lokale Bauteilbezeichnung ohne echte Aufnahme',installed_position:'SIMULATION A',condition:'SIMULATION',storage_location:'SIMULATION',person:'UX AUDIT'}))await p.locator(`#instance-form [name="${key}"]`).fill(value);await p.locator('#instance-form [name="observed"]').check();await p.locator('#instance-form button[type="submit"]').click();await capture(p,'journey-partner-empty');const registered=await p.locator('#instance-list').innerText();await p.locator('#close-register').click();await p.locator('#open-index').focus();await p.keyboard.press('Enter');await p.keyboard.press('Tab');const focus=await p.evaluate(()=>({id:document.activeElement.id,text:document.activeElement.textContent?.slice(0,100)}));await capture(p,'journey-keyboard');return {registered,focus,note:'Synthetic test instance, deliberately empty partners/media/event'};});
 await journey('WebGL unavailable fallback',async()=>{const c=await b.newContext({ignoreHTTPSErrors:true});await c.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.includes('webgl'))return null;return original.call(this,type,...args)}});const q=await c.newPage();await ready(q,'werkstatt/');await capture(q,'journey-webgl-fallback');const status=await q.locator('#render-status').innerText();await q.locator('#part-search').fill('Kumpf');await q.locator('[data-part="COMP-KUEMPFE"]').click();const sourceCount=await q.locator('#selection a[target="_blank"]').count();await c.close();return {status,sourceCount};});
 await ctx.close();
}catch(e){report.errors.push(e.stack)}finally{report.finished=new Date().toISOString();fs.writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));await b.close()}
