// Narrow follow-up for concrete findings left by browser-audit.mjs; no production changes.
import fs from 'node:fs';import crypto from 'node:crypto';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.UX_PLAYWRIGHT).href),out=process.env.UX_OUTPUT||'test-results/ux-recovery';fs.mkdirSync(out,{recursive:true});
const b=await chromium.launch({executablePath:process.env.KS_CHROMIUM_PATH||undefined,proxy:process.env.HTTPS_PROXY?{server:process.env.HTTPS_PROXY}:undefined,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']}),base='https://jdistlr.github.io/kleines-schaeferrad/',results={started:new Date().toISOString(),browser:b.version(),checks:[]};
async function shot(p,n){await p.screenshot({path:`${out}/${n}.png`,fullPage:true});fs.writeFileSync(`${out}/${n}.txt`,await p.locator('body').innerText())}
async function check(name,fn){try{results.checks.push({name,executed:true,...await fn()})}catch(e){results.checks.push({name,executed:false,error:e.stack})}fs.writeFileSync(`${out}/followup.json`,JSON.stringify(results,null,2))}
try{
const c=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:390,height:844},acceptDownloads:true}),p=await c.newPage();p.setDefaultTimeout(12000);
await check('water via visible index, resume and stale query',async()=>{await p.goto(base+'feld/');await p.waitForFunction(()=>document.querySelector('#field-storage').textContent==='Lokal gesichert');const visibility=await p.locator('a[href="?task=TASK-WATER"]').isVisible();await p.locator('#open-index').click();await shot(p,'followup-mobile-task-index');await p.locator('[data-task="16"]').click();await shot(p,'followup-mobile-water');const title=await p.locator('#task-title').innerText();await p.locator('[data-field="person"]').fill('UX AUDIT SIMULATION');for(let i=0;i<3;i++)await p.locator('#field-next').click();await p.locator('[data-field="unknown"]').check();await p.locator('[data-field="reason"]').fill('SIMULATION no operating evidence');await p.locator('#field-next').click();await p.locator('#field-next').click();const next=await p.locator('#task-title').innerText();await p.reload();await p.waitForFunction(()=>document.querySelector('#field-storage').textContent==='Lokal gesichert');const afterNormalReload=await p.locator('#task-title').innerText();await p.goto(base+'feld/?task=TASK-WATER');await p.waitForFunction(()=>document.querySelector('#field-storage').textContent==='Lokal gesichert');await p.locator('#field-next').click();await p.reload();await p.waitForFunction(()=>document.querySelector('#field-storage').textContent==='Lokal gesichert');await shot(p,'followup-query-resume');return {waterLinkVisible:visibility,title,next,afterNormalReload,queryReloadProgress:await p.locator('#task-progress').innerText(),queryReloadTitle:await p.locator('#task-title').innerText()}});
await check('mobile measurements, removed media and tampered import',async()=>{await p.goto(base+'feld/');await p.locator('#open-index').click();await p.locator('[data-task="1"]').click();await p.locator('[data-field="person"]').fill('UX AUDIT SIMULATION');await p.locator('#field-next').click();const image=fs.readFileSync('evidence/raw/IMG_6858.jpeg');await p.locator('#field-photos').setInputFiles({name:'SIMULATION.jpeg',mimeType:'image/jpeg',buffer:image});await p.waitForFunction(()=>document.querySelectorAll('.media-line').length===1&&!document.querySelector('#field-next').disabled);await shot(p,'followup-mobile-photo');await p.locator('[data-remove]').click();await p.waitForFunction(()=>document.querySelectorAll('.media-line').length===0);await p.locator('#field-next').click();await p.locator('[data-field="measurement.value"]').fill('123');await p.locator('[data-field="measurement.a"]').fill('SIMULATION endpoint label with long part and partner identifiers KS-KUM-999 / KS-KRU-999');await shot(p,'followup-mobile-measurement');await p.locator('#open-backup').click();const d=p.waitForEvent('download');await p.locator('#field-export').click();const dl=await d,f=`${out}/test-export.json`;await dl.saveAs(f);const packet=JSON.parse(fs.readFileSync(f));const references=Object.values(packet.session.responses).reduce((s,r)=>s+r.media.length,0);const budget=await p.locator('#storage-budget').innerText();await shot(p,'followup-removed-photo-budget');packet.media[0].sha256='0'.repeat(64);fs.writeFileSync(f,JSON.stringify(packet));await p.locator('#field-import').setInputFiles(f);await p.waitForFunction(()=>document.querySelector('#field-error').textContent.includes('Prüfsumme'));const error=await p.locator('#field-error').innerText();await shot(p,'followup-bad-hash');fs.unlinkSync(f);return {exportedMedia:packet.media.length,referencedMedia:references,budget,tamperedImport:error}});
await check('mobile menu and keyboard focus',async()=>{await p.goto(base);await p.getByRole('button',{name:/Menü/}).click();await shot(p,'followup-mobile-menu');const nav=await p.locator('#site-navigation').innerText();await p.getByRole('link',{name:'Vor Ort',exact:true}).click();await p.locator('#open-index').focus();await p.keyboard.press('Enter');await p.keyboard.press('Tab');await shot(p,'followup-keyboard-focus');return {nav,active:await p.evaluate(()=>({id:document.activeElement.id,text:document.activeElement.textContent}))}});
await c.close();
await check('reduced motion after camera settles and target hit areas',async()=>{const c=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000},reducedMotion:'reduce'}),p=await c.newPage();await p.goto(base+'werkstatt/');await p.waitForFunction(()=>document.querySelector('#render-status').textContent!=='3D wird geladen …');await p.locator('#scene-mode').selectOption('betrieb');await p.waitForTimeout(3000);const canvas=p.locator('#canvas-host canvas'),a=await canvas.screenshot();await p.waitForTimeout(1200);const bb=await canvas.screenshot();fs.writeFileSync(`${out}/followup-reduced-a.png`,a);fs.writeFileSync(`${out}/followup-reduced-b.png`,bb);const labels=await p.locator('.quick-layers label,.inline-check').evaluateAll(es=>es.map(e=>({text:e.textContent,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));const result={status:await p.locator('#operation-status').innerText(),changed:!a.equals(bb),labels,match:await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches)};await shot(p,'followup-reduced-motion');await c.close();return result});
}catch(e){results.error=e.stack}finally{results.finished=new Date().toISOString();fs.writeFileSync(`${out}/followup.json`,JSON.stringify(results,null,2));await b.close()}
