import {propertyReadiness} from '../control/property-readiness.mjs';
import {readContext,contextQuery,boundedParameter} from '../control/context.mjs';
import {db,context} from './data.js';
import {isImageAsset} from './assets.mjs';
import language from '../../data/field-language.json';
const partLabel=c=>({'COMP-HUB-LAND':'Armzone Seite A','COMP-HUB-WATER':'Armzone Seite B','COMP-RIM-LAND':'Kranz Seite A','COMP-RIM-WATER':'Kranz Seite B','COMP-ARMS':'Arme · Endpaarung noch offen','COMP-PADDLES':'Schaufeln / Flügelbretter'}[c.id]||c.label);
import {config} from './geometry.mjs';
import {SCHEMA,openStore,readStore,writeStore,validateRecord,mergeImport} from './records.js';
import {createViewer} from './viewer.js';
const $=id=>document.getElementById(id),form=$('capture-form'),base=$('workbench').dataset.base;
const human=s=>String(s??'').replaceAll('→',' bis ').replaceAll('LAND/WATER','Land- und Wasserseite').replaceAll('Datumspunkt','Bezugspunkt').replaceAll('Datum','Bezugspunkt');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={measurement:'Messung',observation:'Beobachtung',identification:'Identifikation','expert-narrative':'Erfahrung aus der Werkstatt',risk:'Risiko'};
const evidenceLabel={'historical-drawing':'alte Zeichnung','observed-current':'heutiger Zustand',measured:'Quellenmessung · Geltungsbereich prüfen','external-context':'Kontextquelle',inferred:'Arbeitsannahme',conflicting:'widersprüchlich',unknown:'noch offen','expert-narrative':'Torstens Fachauskunft',derived:'Ableitung'};
let state={schema:SCHEMA,records:[],selection:'COMP-SHAFT',slot:null,draft:null,viewer:{}},store=null,viewer=null,step=1,media=[],queue=Promise.resolve(),ready=false;
const field=n=>form.elements.namedItem(n);
const requestedContext=readContext(location.search,db.components,db.gaps),navigationParams=new URLSearchParams(location.search);
function navigation(){
 const c=context(state.selection),property=field('question_id').value||c.gaps[0].id,q=contextQuery({part:state.selection,property,from:requestedContext.from});
 if(/^TASK-[A-Z0-9-]+$/.test(navigationParams.get('task')||'')){q.set('task',navigationParams.get('task'));if(/^[0-4]$/.test(navigationParams.get('step')||''))q.set('step',navigationParams.get('step'))}
 const text=document.getElementById('work-question-context');if(text)text.textContent=partLabel(c.component)+' · '+(db.gaps.find(g=>g.id===property)?.subject||'Eigenschaft offen');
 for(const [id,route] of [['cp-return',requestedContext.from==='water'?'control/water/':requestedContext.from==='evidence'?'control/evidence/':'control/'],['bridge-water','control/water/'],['bridge-evidence','control/evidence/'],['bridge-tool','feld/'],['work-field-link','feld/']]){
  const a=document.getElementById(id);if(!a)continue;const target=new URLSearchParams(q);if(route==='feld/'&&property==='GAP-07')target.set('task','TASK-WATER');a.href=base+route+'?'+target;
 }
 const url=new URL(location.href);url.searchParams.set('part',state.selection);url.searchParams.set('property',property);history.replaceState(null,'',url);
}

function snapshot(){return structuredClone({...state,draft:{values:formValues(),media,step,component_id:state.selection,slot:state.slot}})}
function formValues(){const v=Object.fromEntries(new FormData(form));v.unknown=field('unknown').checked;return v}
async function persist(){if(!ready)return false;const data=snapshot();if(!store){$('storage-status').textContent='Speicher nicht verfügbar: Daten nur in dieser Sitzung. Jetzt JSON exportieren.';return false}queue=queue.catch(()=>{}).then(()=>writeStore(store,data));try{await queue;$('storage-status').textContent=`Lokal gesichert · ${state.records.length} Einträge · noch nicht gemeinsam geprüfte Einträge`;$('draft-status').textContent='Entwurf lokal gesichert';return true}catch(e){$('storage-status').textContent='Speichern fehlgeschlagen: Browser-Speicher prüfen und JSON exportieren. Daten bleiben in dieser Sitzung.';$('draft-status').textContent='Nicht dauerhaft gesichert';return false}}
function sourceLink(id){const a=db.manifest.assets.find(x=>x.id===id);return a?.archive?.path?`${base}${a.archive.path.split('/').map(encodeURIComponent).join('/')}`:id==='EXT-VZO-INFO'?'https://www.verein-zufriedenheit.com/info.html':`https://github.com/jdistlr/kleines-schaeferrad/blob/main/evidence/manifest.json`}
function sources(ids){return ids.map(id=>`<a href="${esc(sourceLink(id))}" target="_blank" rel="noopener">${esc(id)}</a>`).join(' · ')}
function options(node,values,placeholder){node.innerHTML=(placeholder?`<option value="">${placeholder}</option>`:'')+values.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('')}
const norm=s=>String(s??'').toLocaleLowerCase('de-DE').normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/ß/g,'ss');
function parts(){const raw=$('part-search').value,q=norm(raw);const alias=q.includes('schetter')?'COMP-SCHETTERNBRETTER':q.includes('zwicker')||q.includes('keil')?'COMP-FASTENERS':q.includes('anwell')?'COMP-BEARINGS':null;$('part-list').innerHTML=db.components.filter(c=>!q||norm(`${c.label} ${c.id}`).includes(q)||c.id===alias).map(c=>`<button data-part="${c.id}" aria-pressed="${c.id===state.selection}">${esc(partLabel(c))}</button>`).join('')||'<p>Kein Treffer. Begriff kürzen oder „Keil“, „Kumpf“, „Arm“ versuchen.</p>';$('part-list').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.part));}
function inspector(){const c=context(state.selection);const evidence=db.reconstruction.find(r=>r.component===state.selection)||db.reconstruction.find(r=>r.component===(state.selection.includes('FRAME')||state.selection==='COMP-BEARING-STANDS'?'COMP-RADSTATT':state.selection.includes('KUMPF')?'COMP-KUEMPFE':state.selection.includes('HUB')?'COMP-ARMS':state.selection.includes('RIM')?'COMP-KRUEMMLINGE':state.selection));if(!c.component)return;const recordCount=state.records.filter(r=>r.component_ids.includes(state.selection)&&!r.retracted).length;const ids=[...new Set([...(evidence?.sources||[]),...c.component.provenance,...c.claims.flatMap(x=>x.provenance.map(p=>p.source_id))])];const photos=ids.filter(id=>db.manifest.assets.find(a=>a.id===id&&isImageAsset(a))).slice(0,5);const gap=(requestedContext.part===state.selection&&db.gaps.find(g=>g.id===requestedContext.property))||c.gaps[0];
 $('selection').innerHTML=`<div class="selection-title"><p class="eyebrow">Ausgewählt</p><h3>${esc(partLabel(c.component))}</h3><p>${esc('Form und aktuelle Maße sind noch nicht nachgemessen.')}</p><span class="tag">${recordCount} eigene Einträge</span></div>
 <div class="question"><span class="eyebrow">Als Nächstes klären</span><strong>${esc(human(gap.subject))}</strong><p>${esc(human(gap.capture))}</p><a href="#capture">Befund dazu festhalten</a></div>
 <details class="property-readiness"><summary>Eigenschaften: belegt, verwendet, noch benötigt</summary><p>Geometrie, Maß und Verbindung können unterschiedliche Prüfstände haben. Die Eignung gilt immer für einen benannten Zweck; eine vollständige technische Zeichnung ist hier nicht freigegeben.</p>${c.claims.filter(x=>x.id.startsWith('TH-')).map(claim=>{const r=propertyReadiness(claim);return `<article class="claim"><strong>${esc(r.label)}</strong><p><b>Vorliegende Aussage:</b> ${esc(typeof r.sourceValue==='object'?JSON.stringify(r.sourceValue):r.sourceValue)} ${esc(r.unit||'')} · ${esc(evidenceLabel[r.sourceClass]||r.sourceClass)}</p><p><b>Prüfgrenze:</b> ${esc(r.metricStatus)}</p><p><b>Modelleingabe:</b> ${r.modelPath?esc(r.modelPath)+' = '+esc(JSON.stringify(r.modelValue))+' · '+(r.agreement?'quellwertgleich; keine Mesh- oder Ist-Verifikation':'Abweichung prüfen'):'Noch nicht eigenschaftsgenau zugeordnet; keine Übereinstimmung behauptet.'}</p><p><b>Noch benötigt:</b> ${esc(r.missing)}</p><small>${esc(claim.id)} · ${sources(claim.provenance.map(p=>p.source_id))}</small></article>`}).join('')||'<p>Keine direkt zugeordnete Fachauskunft. Quellenbeobachtungen und offene Aufgaben unten prüfen.</p>'}<p><b>Nächster Nachweis:</b> ${esc(human(gap.capture))}</p><p><b>Aufnahmeziel:</b> ${esc(gap.acceptance_evidence)}</p><a href="#capture">Nachweis am ausgewählten Teil erfassen →</a></details>
 <div class="source-images">${photos.map(id=>`<a href="${esc(sourceLink(id))}" target="_blank" rel="noopener"><img src="${esc(sourceLink(id))}" loading="lazy" alt="Quellenbild"/><span>Foto öffnen</span></a>`).join('')}</div>
 ${evidence?`<details><summary>Beobachtung und Rekonstruktion</summary><p><strong>Heute sichtbar:</strong> ${esc(evidence.observed_features)}</p><p><strong>Alte Zeichnung:</strong> ${esc(evidence.historical_geometry)}</p><p><strong>Im Modell:</strong> ${esc(evidence.candidate_geometry)}</p><p><strong>Am Teil klären:</strong> ${esc(evidence.unknown)}</p></details>`:''}
 <details><summary>Noch ungeklärt (${c.conflicts.length})</summary>${c.conflicts.map(x=>`<p><strong>${esc(language.conflicts[x.id]||x.issue)}</strong><br><small>${sources(x.sources)}</small></p>`).join('')||'<p>Kein eigener Widerspruch zugeordnet. Unbekannte Stellen können trotzdem offen sein.</p>'}</details>
 <details><summary>Technische Quelldaten (${c.claims.length})</summary>${c.claims.map(x=>`<article class="claim"><span class="tag">${esc(evidenceLabel[x.evidence_class]||x.evidence_class)}</span><p>${esc(x.predicate)}<span class="claim-value">${esc(typeof x.value==='object'?JSON.stringify(x.value):x.value)} ${esc(x.unit??'')}</span></p><small>${x.provenance.map(p=>sources([p.source_id])).join(' · ')}</small></article>`).join('')||'<p>Keine eigenen Aussagen hinterlegt.</p>'}</details>
 <details><summary>Technische Verbindungsdaten</summary>${c.relations.map(r=>`<p>${esc(r.type)} · ${sources(r.provenance)}</p>`).join('')}${c.gaps.map(g=>`<p>${esc(g.subject)}</p>`).join('')}</details>
 <details><summary>Fragen an die Werkstatt</summary>${c.risks.map(r=>`<p><strong>${esc(r.label)}</strong><br>${esc(r.prompt)}</p>`).join('')||'<p>Erfahrung oder Warnsignal direkt am Teil festhalten.</p>'}</details>
 <details><summary>Technische Details</summary><p><small>Interne ID: ${esc(state.selection)}${state.slot?' · Arbeitsposition '+esc(state.slot):''}</small></p><p>Die folgenden Werte steuern nur das Arbeitsmodell. Sie sind keine bestätigten Ist-Maße.</p>${Object.entries(config.parameters).map(([k,v])=>`<p><strong>${esc(k)}</strong>: ${esc(v.value??'offen')}<br><small>${esc(v.note)} · ${esc(v.provenance.join(', '))}</small></p>`).join('')}</details>`;
 $('capture-context').textContent=partLabel(c.component);
 const previous={question_id:field('question_id').value,claim_id:field('claim_id').value,relation_id:field('relation_id').value};options(field('question_id'),[...new Map([...c.gaps,gap].map(g=>[g.id,g])).values()].map(g=>[g.id,g.subject]));options(field('claim_id'),c.claims.map(x=>[x.id,x.predicate]),'Keine konkrete Aussage');options(field('relation_id'),c.relations.map(x=>[x.id,x.type]),'Noch nicht zugeordnet');for(const [key,val] of Object.entries(previous))if([...field(key).options].some(o=>o.value===val))field(key).value=val;
}
function select(id,slot=null){if(!db.components.some(c=>c.id===id))return;
 // Do not silently transfer an unfinished record to a different component.
 if(ready&&id!==state.selection&&(field('feature').value.trim()||media.length)){if(!confirm('Der Entwurf gehört zum bisherigen Teil. Auswahl wechseln und den Entwurf verwerfen? Bereits gespeicherte Einträge bleiben erhalten.'))return;form.reset();media=[];step=1;showStep()}
 state.selection=id;state.slot=slot;inspector();parts();viewer?.select(id);renderMedia();navigation();persist();}
function kindFields(){const kind=field('kind').value;form.querySelectorAll('[data-kinds]').forEach(n=>n.hidden=!n.dataset.kinds.split(',').includes(kind));const required=['value','endpoint_a','endpoint_b','tool','uncertainty'];for(const n of required)field(n).required=kind==='measurement'&&!field('unknown').checked;field('quote').required=['expert-narrative','risk'].includes(kind)&&!field('unknown').checked;field('feature').required=!field('unknown').checked;}
function showStep(){form.querySelectorAll('[data-step]').forEach(n=>n.hidden=Number(n.dataset.step)!==step);$('step-indicator').textContent=`Schritt ${step} von 3 · ${['Befund','Kontext','Prüfen & speichern'][step-1]}`;$('step-back').hidden=step===1;$('step-next').hidden=step===3;$('save-record').hidden=step!==3;$('step-next').textContent=step===1?'Weiter zum Kontext':'Weiter zur Prüfung';if(step===3)review();kindFields();}
function stepValid(){const fieldset=form.querySelector(`[data-step="${step}"]`);for(const el of fieldset.querySelectorAll('input,select,textarea')){if(el.closest('[data-kinds]')?.hidden)continue;if(!el.checkValidity()){el.reportValidity();return false}}return true}
function record(){const v=formValues(),c=context(state.selection);return {id:'OBS-'+crypto.randomUUID(),schema:SCHEMA,question_id:v.question_id,event_id:v.event_id,component_ids:[state.selection],slot_id:state.slot,physical_id:v.physical_id||null,relation_ids:v.relation_id?[v.relation_id]:[],partner_ids:v.partners.split(',').map(x=>x.trim()).filter(Boolean),kind:v.kind,feature:v.feature,value:v.kind==='measurement'&&!v.unknown?Number(v.value):null,unit:v.kind==='measurement'?v.unit:null,endpoints:v.kind==='measurement'?{a:v.endpoint_a,b:v.endpoint_b}:null,tool:v.tool||null,uncertainty:v.kind==='measurement'&&!v.unknown?Number(v.uncertainty):null,side:v.side,state:v.state,person:v.person,timestamp:new Date().toISOString(),media:[...media,...(v.media_reference?[{id:'REF-'+crypto.randomUUID(),name:v.media_reference,role:v.media_role,external:true}]:[])],quote:v.quote||null,interpretation:v.interpretation||null,confidence:v.confidence,unknown:!!v.unknown,variant:v.kind==='identification'?v.variant:null,orientation:v.orientation||null,storage_location:v.storage_location||null,claim_ids:v.claim_id?[v.claim_id]:[],conflict_ids:c.conflicts.map(x=>x.id),effect:v.effect,review_status:'unreviewed-local',craft:v.kind==='risk'?{topic:v.risk_topic,trigger:v.trigger,mechanism:v.mechanism,expected_behaviour:v.expected_behaviour,failure_consequence:v.failure_consequence,warning_sign:v.warning_sign,mitigation:v.mitigation,source_person:v.person,alternate_account:v.alternate_account}:null};}
function review(){const r=record(),ctx=context(state.selection),gap=db.gaps.find(g=>g.id===r.question_id),claim=r.claim_ids.length?db.claims.find(x=>x.id===r.claim_ids[0]):null;const side={UNKNOWN:'Seite noch offen',LAND:'Landseite',WATER:'Wasserseite'}[r.side]||r.side,stateName={installed:'eingebaut','during-release':'beim Lösen',removed:'ausgebaut'}[r.state]||r.state,effect={context:'ergänzt unser Bild',supports:'bestätigt die ausgewählte Aussage',challenges:'passt nicht zur ausgewählten Aussage'}[r.effect]||r.effect;$('review').innerHTML=`<p><strong>${esc(labels[r.kind])}</strong> · ${esc(gap?.subject||'offene Frage')} · ${esc(partLabel(ctx.component))}</p><p>${esc(r.feature||'Noch nicht bekannt / nicht zugänglich')}</p>${r.kind==='measurement'&&!r.unknown?`<p><strong>${r.value} ${esc(r.unit)} ± ${r.uncertainty}</strong><br>${esc(r.endpoints.a)} bis ${esc(r.endpoints.b)} · ${esc(r.tool)}</p>`:''}<p>${esc(r.person)} · Ereignis ${esc(r.event_id)} · ${esc(side)} · ${esc(stateName)}</p><p>${r.media.length} Medien · ${esc(effect)}${claim?`: „${esc(claim.predicate)}“`:''}</p><p>${ctx.conflicts.length?ctx.conflicts.length+' noch ungeklärte Punkte werden berührt.':'Kein eigener Widerspruch zugeordnet.'} Der Befund wartet auf die gemeinsame Prüfung.</p>`;}

function renderMedia(){$('media-list').innerHTML=media.map((m,i)=>`<div><img class="media-thumb" src="${esc(m.data_url)}" alt="${esc(m.name)}"/><small>${esc(m.name)} · ${esc(m.role)}</small> <button type="button" data-remove-media="${i}">Foto entfernen</button></div>`).join('');$('media-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{media.splice(Number(b.dataset.removeMedia),1);renderMedia();persist()})}
function records(){$('record-count').textContent=state.records.filter(r=>!r.retracted).length;$('record-list').innerHTML=state.records.map(r=>{const gap=db.gaps.find(g=>g.id===r.question_id),comp=db.components.find(x=>x.id===r.component_ids[0]);return `<article class="record"><strong>${esc(labels[r.kind])} · ${esc(gap?.subject||'offene Frage')}</strong><p>${esc(r.feature||'Noch nicht bekannt / nicht zugänglich')}</p><small>${esc(comp?partLabel(comp):'Teil')} · ${esc(r.person)} · ${esc(new Date(r.timestamp).toLocaleString('de-DE'))} · ${r.retracted?'zurückgezogen':'noch gemeinsam prüfen'}</small><p>${r.media.length} Medien</p><details><summary>Technische Details des Eintrags</summary><pre>${esc(JSON.stringify({...r,media:r.media.map(m=>({...m,data_url:m.data_url?'[Bildbytes im Export]':undefined}))},null,2))}</pre>${r.media.filter(m=>m.data_url).map(m=>`<img class="media-thumb" src="${esc(m.data_url)}" alt="${esc(m.name)}"/>`).join('')}</details>${!r.retracted?`<button data-retract="${esc(r.id)}">Eintrag zurückziehen</button>`:''}</article>`}).join('')||'<p>Noch kein Eintrag. Wähle ein Teil und erfasse die erste Beobachtung.</p>';$('record-list').querySelectorAll('[data-retract]').forEach(b=>b.onclick=()=>{const r=state.records.find(x=>x.id===b.dataset.retract);r.retracted=true;r.retracted_at=new Date().toISOString();records();inspector();persist()});}
function restoreDraft(d){if(!d?.values)return;for(const [name,value] of Object.entries(d.values)){const el=field(name);if(!el||el.type==='file')continue;if(el.type==='checkbox')el.checked=!!value;else el.value=value}media=Array.isArray(d.media)?d.media:[];step=[1,2,3].includes(d.step)?d.step:1;showStep();renderMedia();$('draft-status').textContent='Unterbrochene Aufgabe wiederhergestellt';}
$('part-search').oninput=parts;
$('capture-actions').querySelectorAll('button').forEach(b=>b.onclick=()=>{field('kind').value=b.dataset.kind;step=1;showStep();persist();$('capture-form').scrollIntoView({behavior:'smooth',block:'start'})});
$('step-next').onclick=()=>{if(!stepValid())return;step++;showStep();persist();$('step-indicator').scrollIntoView({block:'nearest'})};$('step-back').onclick=()=>{step--;showStep();persist()};
form.oninput=()=>{kindFields();if(step===3)review();persist()};form.onchange=()=>{kindFields();if(step===3)review();navigation();persist()};
form.onsubmit=async e=>{e.preventDefault();$('form-error').textContent='';try{if(!stepValid())return;const r=record();if(['supports','challenges'].includes(r.effect)&&!r.claim_ids.length)throw Error('Für Stützen/Widersprechen bitte eine Aussage wählen.');validateRecord(r);state.records.push(r);const saved=await persist();records();inspector();form.reset();media=[];step=1;showStep();renderMedia();await persist();$('draft-status').textContent=saved?'Eintrag lokal gesichert · neue Erfassung bereit':'Eintrag nur in dieser Sitzung · jetzt exportieren';$('records').scrollIntoView({behavior:'smooth',block:'start'})}catch(err){$('form-error').textContent=err.message}};
$('media-input').onchange=async e=>{const files=[...e.target.files];$('media-status').textContent='Foto wird gesichert …';try{for(const f of files){if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>3*1024*1024)throw Error(`${f.name}: nur JPEG/PNG/WebP bis 3 MB. Größere Originale separat sichern und referenzieren.`);const data_url=await new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>resolve(rd.result);rd.onerror=reject;rd.readAsDataURL(f)});const hash=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());media.push({id:'MEDIA-'+crypto.randomUUID(),name:f.name,type:f.type,bytes:f.size,sha256:[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join(''),role:field('media_role').value,data_url});}renderMedia();await persist();$('media-status').textContent=`${media.length} Foto(s) im Entwurf; Originalbytes im Export.`}catch(err){$('media-status').textContent=err.message}e.target.value=''};
$('export').onclick=()=>{const payload={...snapshot(),exported_at:new Date().toISOString(),baseline:'dd0cd480a4f509a1137ca19a7f9075a8aba0c30a'},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`KS-Feldprotokoll-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100*1024*1024)throw Error('Datei ist größer als 100 MB.');const payload=JSON.parse(await f.text());const merged=mergeImport(state.records,payload);state.records=merged;if(!field('feature').value.trim()&&!media.length&&payload.draft&&db.components.some(c=>c.id===payload.draft.component_id)){state.selection=payload.draft.component_id;state.slot=payload.draft.slot;inspector();parts();restoreDraft(payload.draft);viewer?.select(state.selection)}records();inspector();await persist();$('storage-status').textContent=`${merged.length} Einträge nach Import. Duplikate bleiben unverändert; vorhandene Quellen werden nicht überschrieben.`}catch(err){$('storage-status').textContent=`Import abgebrochen: ${err.message}`}e.target.value=''};
(async()=>{try{store=await openStore();const saved=await readStore(store);if(saved?.schema===SCHEMA){mergeImport([],saved);state=saved}}catch(e){$('storage-status').textContent='Lokaler Speicher nicht verfügbar. Export verwenden.'}if(!db.components.some(c=>c.id===state.selection))state.selection='COMP-SHAFT';
 const hasDraft=Boolean(['feature','value','quote','interpretation','person','physical_id','endpoint_a','endpoint_b'].some(key=>String(state.draft?.values?.[key]||'').trim())||state.draft?.media?.length);
 const preserveDraft=hasDraft&&requestedContext.part&&requestedContext.part!==state.selection;
 if(requestedContext.part&&!preserveDraft)state.selection=requestedContext.part;
 inspector();parts();records();restoreDraft(state.draft);showStep();
 if(requestedContext.property&&!preserveDraft&&[...field('question_id').options].some(o=>o.value===requestedContext.property))field('question_id').value=requestedContext.property;
 if(preserveDraft)$('work-context-notice').textContent='Vorhandener Entwurf am bisherigen Bauteil wurde erhalten. Für den angefragten Bauteilwechsel zuerst den Entwurf sichern oder bewusst wechseln.';
 navigation();const savedViewer=structuredClone(state.viewer||{});ready=true;await persist();setTimeout(()=>{try{viewer=createViewer(base,select,id=>{select(id);$('capture').scrollIntoView({behavior:'smooth'})},patch=>{state.viewer={...state.viewer,...patch};persist()});if(Object.keys(savedViewer).length)viewer.restore(savedViewer);viewer.select(state.selection);
 if(navigationParams.get('view')==='betrieb'){$('scene-mode').value='betrieb';$('scene-mode').dispatchEvent(new Event('change'))}
 const level=boundedParameter(navigationParams.get('water'),-2.2,-1.5),rpm=boundedParameter(navigationParams.get('rpm'),.2,5);
 for(const [id,value] of [['water-level',level],['rotation-speed',rpm]])if(value!==null){$(id).value=String(value);$(id).dispatchEvent(new Event('input'))}
 }catch(e){$('render-status').textContent='3D nicht verfügbar. Alle Aufgaben bleiben über Teilfinder, Quellen und Zeichnungen erreichbar.';console.warn('WebGL unavailable',e)}},0);})();

// Flush the existing write queue before leaving for another workspace.
document.querySelectorAll('a[href]').forEach(a=>{if(a.target==='_blank')return;a.addEventListener('click',async e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||a.getAttribute('href').startsWith('#'))return;e.preventDefault();await queue.catch(()=>{});location.href=a.href})});
