import {calibratedCycle as vesselState,cfg} from './calibration.mjs';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {PLYLoader} from 'three/addons/loaders/PLYLoader.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {makeModel,matchesFamily,disposeModel,views} from './geometry.mjs';
import {solveRegistration} from './mechanics.mjs';
import scanConfig from '../../data/scan-transforms.json';
const viewLabels={gesamt:'Gesamtanlage',land:'Seite A',wasser:'Seite B',welle:'Welle / Arme',kranz:'Kranz',kumpf:'Kumpf / Schaufel',schaufeln:'Schaufeln',tragwerk:'Tragwerk',lager:'Lager',trog:'Trog / Rinne',betrieb:'Betrieb'};
export function createViewer(base,onSelect,onQuestion,onSettings){
 const $=id=>document.getElementById(id),host=$('canvas-host'),scanHost=$('scan-host'),viewport=$('viewport');
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;renderer.setClearColor(0xf1eee7,1);host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Rekonstruiertes Wasserschöpfrad mit Tragwerk und Wasserweg');
 const scanRenderer=new T.WebGLRenderer({antialias:true,alpha:true});scanRenderer.setPixelRatio(Math.min(devicePixelRatio,2));scanHost.append(scanRenderer.domElement);
 const scene=new T.Scene(),scanScene=new T.Scene(),camera=new T.OrthographicCamera(-5,5,4,-4,.1,100),scanCamera=camera.clone();camera.up.set(0,0,1);scanCamera.up.copy(camera.up);scene.add(new T.HemisphereLight(0xffffff,0x777062,2.4));scanScene.add(new T.HemisphereLight(0xffffff,0x777062,2.4));const light=new T.DirectionalLight(0xfff4dc,2.3);light.position.set(-3,-5,9);scene.add(light);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.1;controls.minZoom=.5;controls.maxZoom=8;controls.enabled=true;
 let model,modelMode='brute',overlapDirection=1,paddlePitchDeg=0,nailMapping='A',jetSpeed=cfg.production.jetSpeed,variant='A',exploded=false,cut=false,view='gesamt',selection=null,scan=null,scanType='ply',armShape='dogleg',armLayers='staggered',joinery='staggered',fasteners='pair',mode='gesamt',running=false,angle=0,speed=2.2,waterLevel=-1.95,scanCenter=new T.Vector3(),scanRadius=3,scanCount=0,cameraGoal=null,registration=null;
 const clip=new T.Plane(new T.Vector3(0,-1,0),0),ray=new T.Raycaster(),mouse=new T.Vector2();
 const site=new T.Group(),water=new T.Mesh(new T.PlaneGeometry(15,16,30,30),new T.MeshStandardMaterial({color:0x7396a3,transparent:true,opacity:.50,roughness:.28,metalness:.25,side:T.DoubleSide}));water.position.z=waterLevel;site.add(water);
 const bank=new T.Mesh(new T.BoxGeometry(2.6,16,.38),new T.MeshStandardMaterial({color:0xc9c4ad,roughness:1}));bank.position.set(-4.2,0,-2.24);site.add(bank);
 const flow=new T.Group();for(let i=0;i<12;i++){const ar=new T.ArrowHelper(new T.Vector3(0,1,0),new T.Vector3((i%4)*1.1-.9,Math.floor(i/4)*3-4,waterLevel+.03),.55,0x5a7d8b,.13,.07);flow.add(ar)}site.add(flow);scene.add(site);
 const liquid=new T.Group(),fills=[],streams=[];for(let i=0;i<24;i++){const f=new T.Mesh(new T.SphereGeometry(.115,12,6),new T.MeshBasicMaterial({color:0x4993b1,transparent:true,opacity:.85}));liquid.add(f);fills.push(f);const s=new T.Line(new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(new Float32Array(39),3)),new T.LineBasicMaterial({color:0x2886ae,transparent:true,opacity:.85}));liquid.add(s);streams.push(s)}scene.add(liquid);
 const channelFlow=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(cfg.production.troughX,-1,cfg.production.troughZ+.04),new T.Vector3(cfg.production.troughX,1.25,cfg.production.troughZ-.01),new T.Vector3(-3.8,1.25,cfg.production.troughZ-.17)]),new T.LineBasicMaterial({color:0x287ea0}));liquid.add(channelFlow);
 const pins=[['COMP-SHAFT','01',[0,0,0]],['COMP-KRUEMMLINGE','02',[-.58,-1.6,1.35]],['COMP-KUEMPFE','03',[-.8,1.8,.8]],['COMP-BEARINGS','04',[-1.6,0,-.1]]].map(([family,text,point])=>{const el=document.createElement('button');el.className='pin';el.textContent=text;el.setAttribute('aria-label',`Aufnahmestelle ${text}`);el.onclick=()=>onQuestion(family);$('pins').append(el);return {el,point}});
 function build(){if(model){scene.remove(model);disposeModel(model)}model=makeModel(variant,exploded?Number($('explode-factor')?.value||1):0,{armShape,armLayers,joinery,fasteners,modelMode,overlapDirection,paddlePitchDeg,nailMapping});for(const m of model.children){m.userData.homePosition=m.position.clone();m.userData.homeRotation=m.quaternion.clone()}scene.add(model);Object.assign(renderer.domElement.dataset,{modelMode,meshCount:String(model.children.length),stationaryCount:String(model.children.filter(m=>m.userData.stationary).length),nailPathCount:String(model.children.filter(m=>m.userData.nailPath).length)});apply()}
 const familyForMode={welle:['COMP-SHAFT','COMP-ARMS','COMP-FASTENERS'],kranz:['COMP-KRUEMMLINGE','COMP-FASTENERS'],kumpf:['COMP-KUEMPFE','COMP-KUMPF-BASE','COMP-KUMPF-HOOPS','COMP-KUMPF-NAILS','COMP-FASTENERS','COMP-PADDLES'],lager:['COMP-BEARINGS','COMP-BEARING-STANDS','COMP-SHAFT'],trog:['COMP-TROUGH']};
 function apply(){if(!model)return;const focus=familyForMode[mode],isolate=$('isolate')?.checked;for(const m of model.children){const focused=focus?focus.includes(m.userData.family):mode==='tragwerk'?m.userData.stationary:mode==='radkoerper'?!m.userData.stationary:true;
  m.visible=(m.userData.stationary?$('layer-stationary').checked:$('layer-model').checked)&&(!isolate||focused);m.material.transparent=!focused||mode==='evidenz';m.material.opacity=!focused?.13:mode==='evidenz'?.7:1;m.material.color.setHex(selection&&matchesFamily(m,selection)?0xd9b354:mode==='evidenz'?(m.userData.hiddenCandidate||m.userData.fastenerCandidate?0xbe914e:m.userData.stationary?0xa3a19c:0xb2a992):m.userData.baseColor);m.material.clippingPlanes=cut?[clip]:[];m.material.wireframe=$('layer-historical').checked&&m.userData.hiddenCandidate;}
 site.visible=modelMode==='brute'&&['gesamt','betrieb'].includes(mode)&&!exploded;liquid.visible=modelMode==='brute'&&mode==='betrieb';$('pins').hidden=!$('layer-questions').checked||mode==='betrieb';$('operation-panel').hidden=mode!=='betrieb';$('evidence-key').hidden=mode!=='evidenz';$('evidence-comparison').hidden=mode!=='evidenz';$('scan-settings').hidden=mode!=='scan';$('scan-status').hidden=mode!=='scan';render();}
 function standard(name,instant=false){view=name;const target=new T.Vector3(),zoom=['kumpf','lager','trog'].includes(name)?1.8:name==='welle'?1.4:1;if(name==='kumpf')target.set(-.6,0,1.8);if(name==='lager')target.set(-1.4,0,-.1);if(name==='trog')target.set(-1.5,0,1.4);const pos=target.clone().add(new T.Vector3(...(views[name]||views.gesamt)));cameraGoal={target,pos,zoom};if(instant){camera.position.copy(pos);controls.target.copy(target);camera.zoom=zoom;camera.lookAt(target);cameraGoal=null}document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));$('view-label').textContent=`${viewLabels[name]||'Gesamtanlage'} · technisch rekonstruiert${exploded?' · auseinandergezogen':''}${cut?' · Schnitt':''}`;onSettings({view,variant,exploded,cut,armShape,armLayers,mode});apply()}
 function render(){const r=host.getBoundingClientRect(),aspect=Math.max(r.width,1)/Math.max(r.height,1);const halfHeight=Math.max(3.6,4.2/aspect);camera.left=-halfHeight*aspect;camera.right=halfHeight*aspect;camera.top=halfHeight;camera.bottom=-halfHeight;camera.updateProjectionMatrix();renderer.render(scene,camera);if(scan&&mode==='scan'){const sr=scanHost.getBoundingClientRect(),aspect=Math.max(sr.width,1)/Math.max(sr.height,1),half=scanRadius*1.15;scanCamera.left=-half*aspect;scanCamera.right=half*aspect;scanCamera.top=half;scanCamera.bottom=-half;scanCamera.zoom=1;scanCamera.position.copy(scanCenter).add(camera.position.clone().sub(controls.target).normalize().multiplyScalar(Math.max(scanRadius*3,10)));scanCamera.lookAt(scanCenter);scanCamera.updateProjectionMatrix();scanRenderer.render(scanScene,scanCamera)}const origin=new T.Vector3().project(camera);for(const [axis,v]of Object.entries({X:[1,0,0],Y:[0,1,0],Z:[0,0,1]})){const e=new T.Vector3(...v).project(camera).sub(origin),l=Math.hypot(e.x,e.y)||1;$('axis-'+axis).setAttribute('x2',42+e.x/l*29);$('axis-'+axis).setAttribute('y2',42-e.y/l*29);$('label-'+axis).setAttribute('x',42+e.x/l*37);$('label-'+axis).setAttribute('y',46-e.y/l*37)}for(const p of pins){const v=new T.Vector3(...p.point).project(camera);p.el.style.left=`${(v.x+1)*r.width/2}px`;p.el.style.top=`${(1-v.y)*r.height/2}px`;p.el.hidden=Math.abs(v.x)>.95||Math.abs(v.y)>.85}}
 function resize(){for(const [h,r]of[[host,renderer],[scanHost,scanRenderer]]){const b=h.getBoundingClientRect();r.setSize(Math.max(1,b.width),Math.max(1,b.height),false)}render()}new ResizeObserver(resize).observe(viewport);
 function rotateModel(){const q=new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),angle);for(const m of model.children)if(!m.userData.stationary){m.position.copy(m.userData.homePosition).applyQuaternion(q);m.quaternion.copy(q).multiply(m.userData.homeRotation)}}
 let last=performance.now();function tick(now){const dt=Math.min((now-last)/1000,.05);last=now;if(cameraGoal){camera.position.lerp(cameraGoal.pos,.12);controls.target.lerp(cameraGoal.target,.12);camera.zoom+=(cameraGoal.zoom-camera.zoom)*.12;if(camera.position.distanceTo(cameraGoal.pos)<.005){cameraGoal=null}}controls.update();if(running&&mode==='betrieb')angle+=dt*speed*Math.PI/30;rotateModel();let discharge=0;for(let i=0;i<24;i++){const state=vesselState(angle+i*Math.PI/12,{waterLevel,overlapDirection,paddlePitchDeg,jetSpeed,rotationRPM:speed}),f=fills[i];f.visible=state.fill>.01;f.position.set(...state.center);f.scale.set(1,1,Math.max(.05,state.fill*.7));const s=streams[i];s.visible=state.discharging;discharge+=Number(state.inTrough);if(s.visible){const positions=s.geometry.attributes.position;state.stream.forEach((v,j)=>positions.setXYZ(j,...v));positions.needsUpdate=true;s.geometry.computeBoundingSphere()}}channelFlow.visible=discharge>0;for(const a of flow.children){a.position.y+=dt*.3;if(a.position.y>5)a.position.y=-5;a.position.z=waterLevel+.02}water.position.z=waterLevel;$('operation-status').textContent=`${running?'Rad läuft':'Rad angehalten'} · ${speed.toFixed(1).replace('.',',')} U/min · ${discharge?'Wasserübergabe am Trog':'Aufnehmen und Anheben'}`;render();requestAnimationFrame(tick)}
 controls.addEventListener('start',()=>cameraGoal=null);let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const b=host.getBoundingClientRect();mouse.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(model.children).find(h=>h.object.visible&&h.object.material.opacity>.5&&(!cut||h.point.y<=clip.constant));if(hit)onSelect(hit.object.userData.family,hit.object.userData.id)});
 async function setMode(next){mode=next;$('scene-mode').value=mode;$('layer-scan').checked=mode==='scan';scanHost.hidden=mode!=='scan';viewport.classList.toggle('scan-active',mode==='scan');$('scan-separation').hidden=mode!=='scan';if(mode==='scan'){document.querySelector('.technical-settings').open=true;$('scan-settings').open=true;await loadScan()}if(mode==='exploded'){exploded=true;build()}else if(exploded){exploded=false;build()}cut=mode==='schnitt';standard(views[mode]?mode:'gesamt');resize()}
 $('scene-mode').onchange=()=>setMode($('scene-mode').value);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{setMode(b.dataset.view);standard(b.dataset.view)});
 $('reset').onclick=()=>{running=false;$('play').textContent='Rad laufen lassen';$('play').setAttribute('aria-pressed','false');angle=0;selection=null;exploded=false;cut=false;setMode('gesamt');build();standard('gesamt')};$('orbit').onclick=()=>{controls.enabled=!controls.enabled;$('orbit').textContent=`Modell bewegen: ${controls.enabled?'an':'aus'}`;$('orbit').setAttribute('aria-pressed',controls.enabled)};
 $('explode').onclick=()=>{exploded=!exploded;$('explode').setAttribute('aria-pressed',exploded);$('explode').textContent=`Auseinanderziehen: ${exploded?'an':'aus'}`;build();standard(view)};$('cut').onclick=()=>{cut=!cut;$('cut').setAttribute('aria-pressed',cut);$('cut').textContent=`Schnitt: ${cut?'an':'aus'}`;apply()};$('cut-offset').oninput=()=>{clip.constant=Number($('cut-offset').value);apply()};$('explode-factor').oninput=()=>{exploded=true;build()};$('isolate').onchange=apply;
 $('variant').onclick=()=>{variant=variant==='A'?'B':'A';$('variant').textContent=`Dauben ${variant==='A'?24:22} mm · historische Variante`;build()};for(const id of['model','stationary','historical','questions'])$('layer-'+id).onchange=apply;$('layer-scan').onchange=()=>setMode($('layer-scan').checked?'scan':'gesamt');
 $('arm-shape').onchange=()=>{armShape=$('arm-shape').value;build()};$('arm-layers').onchange=()=>{armLayers=$('arm-layers').value;build()};$('joinery').onchange=()=>{joinery=$('joinery').value;armLayers=joinery==='crossing'?'coplanar':'staggered';$('arm-layers').value=armLayers;build();$('candidate-result').textContent=joinery==='crossing'?'Überlagerung im Inneren: nur mit noch unbelegten Ausklinkungen möglich. Rang 3.':joinery==='independent'?'Einzelne Einsteckarme: Einbau denkbar, durchgehende Endpaarung würde entfallen. Rang 2.':'Axial getrennte Durchsteckarme: kein Arm-Arm-Kontakt bei gewähltem Versatz. Rang 1; Innenform bleibt offen.'};
 $('fastener-variant').onchange=()=>{nailMapping=$('fastener-variant').value;build();$('fastener-note').textContent='A: gleichhohe Lochpaare; B: umgekehrte Einsteckrichtung; C: Kreuzpaarung. Nur A ist führender Kandidat; kein bestätigter Nagelweg.'};
 $('model-mode').onchange=()=>{modelMode=$('model-mode').value;build()};
 $('overlap-direction').onchange=()=>{overlapDirection=Number($('overlap-direction').value);build()};
 $('jet-speed').onchange=()=>jetSpeed=Number($('jet-speed').value);
 $('paddle-pitch').onchange=()=>{paddlePitchDeg=Number($('paddle-pitch').value);build()};

 const comparison={current:['IMG_6812.jpeg','Aktuelles Originalfoto: sichtbarer Zustand, kein metrischer Abgleich.'],historical:['IMG_6790.jpeg','Historischer Radkreis: alte Notationen, keine bestätigten heutigen Maße.'],arm:['IMG_6798.jpeg','Historisches Armprofil: Verlauf belegt, heutige Kröpfung noch am Teil prüfen.']};function showComparison(){const [file,caption]=comparison[$('comparison-source').value];$('comparison-image').src=base+'evidence/raw/'+file;$('comparison-link').href=$('comparison-image').src;$('comparison-caption').textContent=caption}$('comparison-source').onchange=showComparison;showComparison();
 $('play').onclick=()=>{running=!running;$('play').textContent=running?'Anhalten':'Rad laufen lassen';$('play').setAttribute('aria-pressed',running)};$('rotation-speed').oninput=()=>speed=Number($('rotation-speed').value);$('water-level').oninput=()=>waterLevel=Number($('water-level').value);
 async function loadScan(){if(scan){scanScene.remove(scan);scan.traverse(o=>{o.geometry?.dispose();for(const m of[].concat(o.material||[]))m.dispose()});scan=null}$('scan-status').textContent='Scan wird geladen …';try{scanType=$('scan-source').value;if(scanType==='ply'){const g=await new PLYLoader().loadAsync(base+'evidence/raw/Scaniverse%202026-10-07%20173556.ply');scanCount=g.attributes.position.count;scan=new T.Points(g,new T.PointsMaterial({size:1.5,sizeAttenuation:false,vertexColors:g.hasAttribute('color'),color:g.hasAttribute('color')?0xffffff:0x7396a3}))}else {scan=(await new GLTFLoader().loadAsync(base+'evidence/raw/Scaniverse%202026-10-07%20173556.glb')).scene;scanCount=0}scanScene.add(scan);transformScan()}catch(e){$('scan-status').textContent='Scan konnte nicht geladen werden. Originaldatei und Verbindung prüfen.'}resize()}
 function transformScan(){if(!scan)return;const stage=$('scan-stage').value,vals=Object.fromEntries(['x','y','z','scale','rx','ry','rz'].map(k=>[k,Number($('scan-'+k).value)]));if(!Object.values(vals).every(Number.isFinite)||vals.scale<=0)return;const matrix=new T.Matrix4();if(stage!=='RAW_EXPORT')matrix.set(...(scanType==='ply'?scanConfig.ply_axis_normalization:scanConfig.axis_normalization).matrix_row_major);if(stage==='ROUGH_ALIGNED')matrix.premultiply(new T.Matrix4().compose(new T.Vector3(vals.x,vals.y,vals.z),new T.Quaternion().setFromEuler(new T.Euler(...['rx','ry','rz'].map(k=>vals[k]*Math.PI/180))),new T.Vector3(vals.scale,vals.scale,vals.scale)));scan.matrixAutoUpdate=false;scan.matrix.copy(matrix);scan.updateMatrixWorld(true);const b=new T.Box3().setFromObject(scan);if(stage!=='ROUGH_ALIGNED'){scanCenter=b.getCenter(new T.Vector3());scanRadius=Math.max(b.getSize(new T.Vector3()).length()/2,1)}scanHost.querySelector('.scan-panel-label').textContent=scanType==='ply'?'Punktewolke · noch nicht registriert':'Oberflächenmodell · noch nicht registriert';$('scan-status').textContent=`${scanType==='ply'?'Punktewolke':'Oberflächenmodell'} · ${$('scan-stage').selectedOptions[0].text} · ${scanCount?scanCount.toLocaleString('de-DE')+' Punkte · ':''}nicht mechanisch registriert`;onSettings({scan_transform:vals,scan_record:{source:scanType,state:stage,matrix_row_major:matrix.clone().transpose().toArray(),adopted_mechanical_transform:null}});render()}
 $('scan-source').onchange=loadScan;for(const k of['x','y','z','scale','rx','ry','rz'])$('scan-'+k).oninput=transformScan;$('scan-stage').onchange=transformScan;$('scan-reset').onclick=()=>{for(const k of['x','y','z','scale','rx','ry','rz'])$('scan-'+k).value=k==='scale'?'1':'0';$('scan-stage').value='AXIS_NORMALIZED';transformScan()};
 $('solve-registration').onclick=()=>{try{const d=JSON.parse($('datum-input').value);registration=solveRegistration(d.source,d.target,d.axisSource,d.axisTarget,d.control);$('registration-result').textContent=`${registration.passed?'Kontrollprüfung innerhalb Toleranz':'Kontrollprüfung außerhalb Toleranz'} · Restfehler ${(registration.rms*1000).toFixed(1)} mm · Kontrolle ${(registration.controlError*1000).toFixed(1)} mm · Achslage ${(registration.axisPositionError*1000).toFixed(1)} mm · Achswinkel ${registration.axisErrorDeg.toFixed(2)}°. Ergebnis zur gemeinsamen Prüfung; keine automatische Übernahme.`;onSettings({registration_candidate:registration})}catch(e){$('registration-result').textContent=e.message}};
 build();standard('gesamt',true);resize();requestAnimationFrame(tick);$('render-status').textContent='Ziehen: drehen · zwei Finger: verschieben / vergrößern';
 return {select(id){selection=id;apply()},restore(s){if(!s)return;armShape=['dogleg','straight','unknown'].includes(s.armShape)?s.armShape:'dogleg';armLayers=['staggered','coplanar','reverse'].includes(s.armLayers)?s.armLayers:'staggered';$('arm-shape').value=armShape;$('arm-layers').value=armLayers;variant=s.variant==='B'?'B':'A';build();standard(views[s.view]?s.view:'gesamt',true)}};
}
