import {readContext,contextQuery} from '../control/context.mjs';
import gapData from '../../data/knowledge-gaps.json';
import taskData from '../../data/field-tasks.json';
import visualData from '../../data/visual-guides.json';
import {renderGuide} from './visual.js';
import componentData from '../../data/components.json';
import {FIELD_SCHEMA,freshSession,openFieldStore,getSession,saveSession,getMedia,validateInstance,checkTask,validateImport,mergeSessions} from './store.js';
const $=id=>document.getElementById(id),base=$('field-app').dataset.base,tasks=taskData.tasks;
const guideFor=id=>visualData.guides.find(g=>g.id===visualData.task_visual_map[id]);
const componentLabel=id=>(componentData.components.find(c=>c.id===id)?.label||'Teilgruppe noch offen').replace('(mapping to confirm)','· Zuordnung offen');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusNames={OPEN:'Offen',IN_PROGRESS:'In Arbeit',CAPTURED_UNREVIEWED:'Aufgenommen · gemeinsam prüfen',BLOCKED_UNKNOWN:'Noch offen · keine Freigabe'};
let state=freshSession(),db=null,queue=Promise.resolve(),media=new Map(),urls=[],busy=false;
const incomingContext=readContext(location.search,componentData.components,gapData.gaps);
const task=()=>tasks[state.task_index];
function navigation(){
 const t=task(),isRequestedTask=new URLSearchParams(location.search).get('task')===t.task_id;
 const context={part:isRequestedTask&&incomingContext.part?incomingContext.part:t.family,property:isRequestedTask&&incomingContext.property?incomingContext.property:(t.source_refs||[]).find(id=>id.startsWith('GAP-'))||null,from:incomingContext.from};
 const q=contextQuery(context);q.set('task',t.task_id);q.set('step',String(state.step));
 const url=new URL(location.href);url.search=q.toString();history.replaceState(null,'',url);
 for(const [id,route] of [['cp-return',context.from==='water'?'control/water/':context.from==='evidence'?'control/evidence/':'control/'],['bridge-water','control/water/'],['bridge-evidence','control/evidence/'],['bridge-tool','werkstatt/']]){const a=$(id);if(a)a.href=base+route+'?'+q;}
}

function response(){return state.responses[task().task_id]||=( {task_id:task().task_id,status:'OPEN',person:state.person,media:[],measurement:{a:task().measurement_endpoints[0],b:task().measurement_endpoints[1],unit:'mm'},unknown:false,reason:'',quote:'',interpretation:'',reviewed:false} )}
function error(e){$('field-error').textContent=e?.message||String(e)}
async function persist(files=[]){if(!db){$('field-storage').textContent='Nur in dieser Sitzung - jetzt sichern';return false}const snapshot=structuredClone(state);queue=queue.catch(()=>{}).then(()=>saveSession(db,snapshot,files));try{await queue;$('field-storage').textContent='Lokal gesichert';return true}catch(e){$('field-storage').textContent='Nicht dauerhaft gesichert - Datei exportieren';error(e);return false}}
function stepNames(){return task().measurement_required?['Auftrag','Fotos','Messung','Erklärung / offen','Prüfen']:['Auftrag','Fotos','Erklärung / offen','Prüfen']}
function screen(id){for(const key of ['task','index','register','backup'])$(key+'-screen').hidden=key!==id;$('field-error').textContent='';if(id==='index')index();if(id==='register')renderInstances();if(id==='backup')budget();window.scrollTo(0,0)}
const input=(name,label,value='',type='text')=>`<label>${esc(label)}<input data-field="${name}" value="${esc(value)}" type="${type}" ${type==='number'?'step="any"':''}/></label>`;
function render(){urls.forEach(URL.revokeObjectURL);urls=[];const t=task(),r=response(),steps=stepNames();state.step=Math.min(state.step,steps.length-1);const name=steps[state.step],guide=guideFor(t.task_id);$('task-title').textContent=t.title;$('task-code').textContent=guide?.sheet||'';$('task-progress').textContent=`Aufgabe ${state.task_index+1} von ${tasks.length} · Schritt ${state.step+1} von ${steps.length}`;$('task-timing').textContent=taskData.timing_labels[t.timing]+' · '+statusNames[r.status];document.querySelectorAll('[data-phase]').forEach(n=>n.classList.toggle('is-active',n.dataset.phase===t.timing));$('task-stop').hidden=!t.stop_before_release||state.step>0;$('field-back').disabled=state.step===0;$('field-next').textContent=name==='Prüfen'?'Aufnahme sichern':'Weiter';$('task-save').textContent=r.status==='BLOCKED_UNKNOWN'?'Noch offen. Dieser Eintrag gibt keine Demontage frei.':'';$('task-visual').innerHTML=guide?renderGuide(guide,name):'';let html='';
 if(name==='Auftrag')html=`<div class="task-instruction"><strong>Jetzt:</strong><p>${esc(t.instruction)}</p></div><div class="task-meta"><span><strong>${esc(t.capture_priority?.priority||t.priority)} · ${esc(t.capture_priority?.window||"")}</strong> ${esc(t.irreversible_loss)}</span><span><strong>Mitnehmen:</strong> ${t.tools.map(esc).join(', ')}</span></div><div class="task-person">${input('person','Person / Kürzel',r.person)}${input('physical_id','Teil-ID, falls bereits beschriftet',r.physical_id)}</div><p class="fineprint">${esc(componentLabel(t.family))} · Form und Maße bleiben offen, bis sie am echten Rad aufgenommen wurden.</p>`;
 if(name==='Fotos'){html=`<label>Welche Ansicht?<select id="photo-view">${t.photo_views.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><label>Foto aufnehmen oder mehrere wählen<span class="file-pick"><input id="field-photos" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" multiple/><span>Datei auswählen</span></span></label><p id="photo-count">${r.media.length} Fotos lokal zugeordnet</p><div id="photo-list">${r.media.map(m=>{const blob=media.get(m.id)?.blob;const url=blob?URL.createObjectURL(blob):'';if(url)urls.push(url);return `<div class="media-line">${url?`<img src="${url}" alt="${esc(m.view)}"/>`:''}<small>${esc(m.name)}<br>${esc(m.view)}</small><button data-remove="${m.id}">Entfernen</button></div>`}).join('')}</div><p>Fehlende Ansichten: ${t.photo_views.filter(v=>!r.media.some(m=>m.view===v)).map(esc).join(', ')||'keine'}. Nicht zugänglich? Im nächsten Schritt offen markieren.</p>`}
 if(name==='Messung'){const m=r.measurement;html=`<p class="step-lead">Die Ansicht zeigt den Arbeitsbereich. Messendpunkte am realen Teil eindeutig bestimmen und hier benennen.</p><div class="measure-grid">${input('measurement.value','Messwert',m.value,'number')}${input('measurement.unit','Einheit',m.unit)}${input('measurement.a','Endpunkt A',m.a)}${input('measurement.b','Endpunkt B',m.b)}${input('measurement.tool','Werkzeug',m.tool)}${input('measurement.uncertainty','Unsicherheit ±',m.uncertainty,'number')}</div>`}
 if(name==='Erklärung / offen')html=`${t.questions.map(q=>`<p><strong>${esc(q)}</strong></p>`).join('')}<label>Wörtliche Erklärung<textarea data-field="quote" rows="3">${esc(r.quote)}</textarea></label><label>Unsere Deutung, getrennt davon<textarea data-field="interpretation" rows="2">${esc(r.interpretation)}</textarea></label>${input('external_media','Separat gesicherte Audio-/Video-Datei',r.external_media)}<label class="check"><input data-field="unknown" type="checkbox" ${r.unknown?'checked':''}/> Weiß ich nicht / noch nicht zugänglich</label><label>Was fehlt oder ist nicht zugänglich?<textarea data-field="reason" rows="2">${esc(r.reason)}</textarea></label>`;
 if(name==='Prüfen')html=`<div class="review-summary"><p><strong>${esc(r.person||'Person fehlt')}</strong> · ${esc(r.physical_id||'Teil-ID noch offen')}</p><p>${r.media.length} Fotos${t.measurement_required?` · ${esc(r.measurement.value??'Maß offen')} ${esc(r.measurement.unit)}`:''}</p><p>${r.unknown?'NOCH OFFEN · '+esc(r.reason):esc(t.acceptance_evidence)}</p></div><label class="check"><input data-field="reviewed" type="checkbox" ${r.reviewed?'checked':''}/>Am echten Teil geprüft.</label><p class="fineprint">Aufgenommen bedeutet noch nicht fachlich freigegeben. Ein offener STOPP bleibt offen.</p>`;
 $('task-content').innerHTML=html;$('task-content').querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{const keys=el.dataset.field.split('.');const target=keys.length===2?r[keys[0]]:r;target[keys.at(-1)]=el.type==='checkbox'?el.checked:el.value;if(keys[0]==='person')state.person=el.value;r.status='IN_PROGRESS';r.updated_at=new Date().toISOString();persist()});
 navigation();$('field-photos')?.addEventListener('change',photos);$('task-content').querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{r.media=r.media.filter(m=>m.id!==b.dataset.remove);r.reviewed=false;r.status='IN_PROGRESS';await persist();render()});}
async function photos(e){if(busy)return;busy=true;$('field-next').disabled=true;$('open-index').disabled=true;try{const r=response(),view=$('photo-view').value,newMedia=[];let total=[...media.values()].reduce((a,m)=>a+m.bytes,0);for(const f of e.target.files){if(!/^image\/(jpeg|png|webp)$/.test(f.type)||f.size>25*1024*1024)throw Error('JPEG/PNG/WebP bis 25 MB verwenden; größere Originale separat sichern.');if(total+f.size>250*1024*1024)throw Error('250 MB Sitzungsgrenze erreicht. Jetzt exportieren; Originale behalten.');const hash=await crypto.subtle.digest('SHA-256',await f.arrayBuffer()),m={id:'MEDIA-'+crypto.randomUUID(),name:f.name,type:f.type,bytes:f.size,sha256:[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join(''),blob:f};media.set(m.id,m);newMedia.push(m);r.media.push({id:m.id,name:m.name,view,sha256:m.sha256});total+=f.size}r.status='IN_PROGRESS';r.reviewed=false;await persist(newMedia);render()}catch(e){error(e);await persist([...media.values()]);render()}finally{busy=false;$('field-next').disabled=false;$('open-index').disabled=false}}
$('field-next').onclick=async()=>{if(busy)return;const steps=stepNames(),r=response();$('field-error').textContent='';if(state.step<steps.length-1){state.step++;await persist();render();window.scrollTo(0,0);return}const problems=checkTask(task(),r);if(problems.length){error(problems.join(' '));return}r.status=r.unknown?'BLOCKED_UNKNOWN':'CAPTURED_UNREVIEWED';r.captured_at=new Date().toISOString();if(!await persist()){error('Noch nicht dauerhaft gespeichert. Sicherung exportieren.');return}state.task_index=Math.min(state.task_index+1,tasks.length-1);state.step=0;await persist();render();$('task-save').textContent='Vorige Aufnahme lokal gesichert. Nächste Aufgabe bereit.';window.scrollTo(0,0)};
$('field-back').onclick=async()=>{state.step=Math.max(0,state.step-1);await persist();render()};
function index(){const filter=$('timing-filter').value;$('task-index').innerHTML=tasks.map((t,i)=>({t,i,guide:guideFor(t.task_id)})).filter(({t})=>!filter||t.timing===filter).map(({t,i,guide})=>`<button class="task-row" data-task="${i}"><strong>${esc(t.title)}</strong><small>${esc(guide?.sheet||'')} · ${taskData.timing_labels[t.timing]} · ${statusNames[state.responses[t.task_id]?.status||'OPEN']}</small></button>`).join('');$('task-index').querySelectorAll('button').forEach(b=>b.onclick=async()=>{state.task_index=Number(b.dataset.task);state.step=0;await persist();screen('task');render()})}
$('timing-filter').onchange=index;for(const key of ['index','register','backup']){$('open-'+key).onclick=()=>screen(key);$('close-'+key).onclick=()=>screen('task')}
function renderInstances(){const f=$('instance-form');for(const [k,v] of Object.entries(state.draft_instance||{})){const el=f.elements.namedItem(k);if(el)el.type==='checkbox'?el.checked=!!v:el.value=v}if(!f.elements.namedItem('person').value)f.elements.namedItem('person').value=state.person;$('instance-list').innerHTML=state.instances.map(i=>`<article class="instance"><strong>${esc(i.id)} · ${esc(i.local_name)}</strong><p>${esc(i.installed_position)} mit ${esc(i.storage_location)}</p><small>Alte Marke: ${esc(i.historic_marks||'offen')} · Partner: ${i.partners.map(esc).join(', ')} · ${esc(i.removal_event||'noch eingebaut')}</small></article>`).join('')||'<p>Noch keine realen Teile eingetragen.</p>'}
$('instance-form').oninput=()=>{const f=$('instance-form');state.draft_instance={...Object.fromEntries(new FormData(f)),observed:f.elements.namedItem('observed').checked};persist()};
$('instance-form').onsubmit=async e=>{e.preventDefault();try{const f=e.target,i={...Object.fromEntries(new FormData(f)),observed:f.elements.namedItem('observed').checked,timestamp:new Date().toISOString()};i.partners=i.partners.split(',').map(x=>x.trim()).filter(Boolean);i.media_ids=i.media_ids.split(',').map(x=>x.trim()).filter(Boolean);validateInstance(i);if(state.instances.some(x=>x.id===i.id))throw Error('ID bereits vergeben. Bestehende Einträge werden nicht überschrieben.');state.instances.push(i);if(i.removal_event)state.events.push({id:i.removal_event+'-'+i.id,event_number:i.removal_event,instance_id:i.id,partners:i.partners,storage_location:i.storage_location,timestamp:i.timestamp,person:i.person,media_ids:i.media_ids});state.draft_instance={};await persist();f.reset();renderInstances()}catch(e){error(e)}};
async function budget(){const estimate=await navigator.storage?.estimate?.();const bytes=[...media.values()].reduce((a,m)=>a+m.bytes,0);$('storage-budget').textContent=`${media.size} Fotos · ${(bytes/1024/1024).toFixed(1)} MB. ${estimate?`Browser: ${(estimate.usage/1024/1024).toFixed(1)} / ${(estimate.quota/1024/1024).toFixed(0)} MB belegt.`:'Speichergrenze nicht bekannt.'} ${estimate&&(estimate.usage/estimate.quota>.7||estimate.quota-estimate.usage<100*1024*1024)?'Wenig freier Speicher - jetzt sichern.':''}`}
$('persist-request').onclick=async()=>{$('backup-status').textContent=await navigator.storage?.persist?.()?'Browser hat dauerhaften Speicher zugesagt. Export bleibt nötig.':'Browser garantiert keine dauerhafte Speicherung. Regelmäßig exportieren.'};
const blob64=b=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(b)});
$('field-export').onclick=async()=>{const button=$('field-export');button.disabled=true;try{await queue.catch(()=>{});const output=[];for(const m of media.values())output.push({...m,blob:undefined,base64:await blob64(m.blob)});const p={schema:FIELD_SCHEMA,task_revision:taskData.revision,exported_at:new Date().toISOString(),session:state,media:output},b=new Blob([JSON.stringify(p)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='KS-Feldsicherung-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);$('backup-status').textContent=`Sicherung erstellt: ${media.size} Fotos. Datei außerhalb des Browsers ablegen und einlesen.`}catch(e){error(e)}finally{button.disabled=false}};
$('field-import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>350*1024*1024)throw Error('Sicherung größer als 350 MB; Originaldatei erhalten.');const p=validateImport(JSON.parse(await f.text()),tasks.map(t=>t.task_id)),newMedia=[];let bytes=0;for(const m of p.media){const raw=atob(m.base64),arr=Uint8Array.from(raw,c=>c.charCodeAt(0));bytes+=arr.length;if(bytes>250*1024*1024||arr.length!==m.bytes)throw Error('Bildgröße stimmt nicht oder Sitzungsgrenze überschritten.');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',arr))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==m.sha256)throw Error('Bild-Prüfsumme stimmt nicht: '+m.name);if(media.has(m.id)&&media.get(m.id).sha256!==hash)throw Error('Widersprüchliche Foto-ID.');const {base64,...meta}=m;newMedia.push({...meta,blob:new Blob([arr],{type:m.type})})}const empty=Object.values(state.responses).every(r=>r.status==='OPEN')&&!state.instances.length&&!media.size;const merged=empty?p.session:mergeSessions(state,p.session);if(!db)throw Error('Speicher fehlt. Original-Sicherung behalten.');await saveSession(db,merged,newMedia);state=merged;for(const m of newMedia)media.set(m.id,m);render();$('backup-status').textContent=`Sicherung eingelesen: ${media.size} Fotos, Prüfsummen bestätigt. Gemeinsam prüfen; keine Ist-Freigabe.`;budget()}catch(e){error(e)}finally{e.target.value=''}};
async function offline(){if(!('serviceWorker' in navigator)){$('offline-status').textContent='Offline-Start hier nicht unterstützt. Papiermappe sichern.';return}try{await navigator.serviceWorker.register(base+'sw.js',{scope:base});await navigator.serviceWorker.ready;const manifest=await fetch(base+'offline-manifest.json').then(r=>r.json());const cache=await caches.open(manifest.cache_name);const checks=await Promise.all(manifest.urls.map(u=>cache.match(u)));if(checks.every(Boolean))$('offline-status').textContent=`Offline bereit · ${manifest.urls.length} Dateien`;else $('offline-status').textContent='Offline-Vorrat unvollständig - online neu laden.'}catch(e){$('offline-status').textContent='Offline-Vorrat nicht bestätigt. Online einmal vollständig laden.'}}
(async()=>{try{db=await openFieldStore();const saved=await getSession(db);if(saved?.schema===FIELD_SCHEMA)state=saved;for(const m of await getMedia(db))media.set(m.id,m)}catch(e){error('Lokaler Speicher nicht verfügbar. Aufnahmen exportieren, bevor diese Seite geschlossen wird.')}const params=new URLSearchParams(location.search),requested=params.get('task');if(requested&&tasks.some(t=>t.task_id===requested)){const target=tasks.findIndex(t=>t.task_id===requested);if(target!==state.task_index)state.step=0;state.task_index=target;const step=params.get('step');if(step!==null&&/^\d+$/.test(step)&&Number(step)<stepNames().length)state.step=Number(step)}if(!Number.isInteger(state.task_index)||state.task_index<0||state.task_index>=tasks.length)state.task_index=0;render();await persist();offline()})();

// Complete queued writes before normal in-app navigation leaves the field page.
document.querySelectorAll('a[href]').forEach(a=>{if(a.target==='_blank')return;a.addEventListener('click',async e=>{if(e.ctrlKey||e.metaKey||e.shiftKey)return;e.preventDefault();await queue.catch(()=>{});location.href=a.href})});
