export const FIELD_SCHEMA='ks-field-session/v1';
const storagePrefix=import.meta.env?.PUBLIC_STORAGE_NAMESPACE;
const fieldDatabase=storagePrefix?storagePrefix+'-pre-disassembly':'ks-pre-disassembly';
export const freshSession=()=>({schema:FIELD_SCHEMA,id:'SESSION-'+crypto.randomUUID(),created_at:new Date().toISOString(),task_index:0,step:0,responses:{},instances:[],events:[],person:'',draft_instance:{}});
export function openFieldStore(){return new Promise((resolve,reject)=>{const r=indexedDB.open(fieldDatabase,1);r.onupgradeneeded=()=>{r.result.createObjectStore('state');r.result.createObjectStore('media',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export function getSession(db){return new Promise((resolve,reject)=>{const r=db.transaction('state').objectStore('state').get('session');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export function saveSession(db,s,media=[]){return new Promise((resolve,reject)=>{const tx=db.transaction(['state','media'],'readwrite');tx.objectStore('state').put(structuredClone(s),'session');for(const m of media)tx.objectStore('media').put(m);tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error||Error('Speichern abgebrochen'));tx.onerror=()=>reject(tx.error)})}
export function getMedia(db){return new Promise((resolve,reject)=>{const r=db.transaction('media').objectStore('media').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export function validateInstance(i){if(!/^KS-(ARM|KRU|KUM|PAD|KEI)-\d{3,}$/.test(i.id))throw Error('Teil-ID: KS-ARM/KRU/KUM/PAD/KEI und mindestens drei Ziffern.');for(const k of ['person','local_name','installed_position','condition','storage_location'])if(!i[k]?.trim())throw Error('Name, Lage, Zustand, Lagerplatz und Person ausfüllen. Unbekannt darf ausdrücklich angegeben werden.');if(i.observed!==true)throw Error('Nur ein wirklich gesehenes und beschriftetes Teil eintragen.');if(!Array.isArray(i.partners)||!Array.isArray(i.media_ids))throw Error('Partner-/Medienliste fehlt.');return i}
export function checkTask(task,r){const errors=[];if(!r.person?.trim())errors.push('Bitte Person / Kürzel angeben.');if(r.unknown){if(!r.reason?.trim())errors.push('Bitte den Grund für „noch offen“ angeben.');return errors;}for(const label of task.photo_views)if(!(r.media||[]).some(m=>m.view===label))errors.push('Foto fehlt: '+label);if(task.measurement_required){const m=r.measurement||{};if(m.value===''||m.value==null||!Number.isFinite(Number(m.value))||m.uncertainty===''||m.uncertainty==null||!Number.isFinite(Number(m.uncertainty))||Number(m.uncertainty)<0||!m.tool?.trim()||!m.a?.trim()||!m.b?.trim())errors.push('Messung mit beiden Endpunkten, Werkzeug und Unsicherheit ergänzen.');}if(task.media_requirements.explanation&&!r.quote?.trim())errors.push('Wörtliche Erklärung festhalten.');if(!r.reviewed)errors.push('Fertigkriterium am echten Teil prüfen und bestätigen.');return errors}
export function validateImport(p,taskIds){if(p?.schema!==FIELD_SCHEMA||!p.session||p.session.schema!==FIELD_SCHEMA||!Array.isArray(p.media)||!Array.isArray(p.session.instances)||!Array.isArray(p.session.events))throw Error('Keine unterstützte Feldsicherung.');for(const [id,r] of Object.entries(p.session.responses||{})){if(!taskIds.includes(id)||!Array.isArray(r.media))throw Error('Unbekannte Aufgabe oder ungültige Medienliste.');}p.session.instances.forEach(validateInstance);const ids=new Set();for(const m of p.media){if(!m.id||ids.has(m.id)||typeof m.base64!=='string'||!/^image\/(jpeg|png|webp)$/.test(m.type)||!Number.isInteger(m.bytes)||m.bytes<0)throw Error('Ungültige oder doppelte Bilddatei.');ids.add(m.id)}for(const r of Object.values(p.session.responses))for(const m of r.media)if(!ids.has(m.id))throw Error('Bildbytes fehlen: '+m.id);return p}
export function mergeSessions(current,incoming){const out=structuredClone(current);for(const [id,r] of Object.entries(incoming.responses)){if(out.responses[id]&&JSON.stringify(out.responses[id])!==JSON.stringify(r))throw Error('Abweichender Aufgabenstand '+id+'. Sicherungen getrennt halten; nichts überschrieben.');out.responses[id]=r}for(const key of ['instances','events'])for(const item of incoming[key]){const old=out[key].find(x=>x.id===item.id);if(old&&JSON.stringify(old)!==JSON.stringify(item))throw Error('Abweichende ID '+item.id+'. Nichts überschrieben.');if(!old)out[key].push(item)}return out}
