// DOM behavior test, not a rendered-browser/layout acceptance.
// Run with NODE_PATH pointing to a jsdom 26 installation.
const {JSDOM,VirtualConsole}=require('jsdom');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');
const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');const dom=new JSDOM(html,{runScripts:'dangerously',virtualConsole:vc});const d=dom.window.document,$=s=>d.querySelector(s);let selections=0;
for(let n=0;n<3;n++){ $('[data-case="'+n+'"]').click();for(const o of [...$('#ks-claim').options]){$('#ks-claim').value=o.value;$('#ks-claim').dispatchEvent(new dom.window.Event('change'));assert.ok(!$('#ks-detail').textContent.includes('undefined'),o.value);assert.ok($('#ks-detail').textContent.includes('Gilt für:'));assert.ok($('#ks-detail').textContent.includes('Nicht als bestätigtes aktuelles Ist-Maß freigegeben.'));selections++;}}
$('[data-case="2"]').click();assert.equal($('#ks-claim').value,'TH-20261009-28');assert.ok($('#ks-detail').textContent.includes('1,94 m'));assert.equal(d.querySelectorAll('[data-parent]').length,2);$('[data-parent="TH-20261009-25"]').click();assert.equal($('#ks-claim').value,'TH-20261009-25');
$('[data-case="0"]').click();assert.ok($('#ks-detail').textContent.includes('370 · Einheit nicht angegeben'));assert.ok($('#ks-detail').textContent.includes('DOC-SHAFT'));
$('[data-case="2"]').click();$('#ks-claim').value='CLAIM-0347';$('#ks-claim').dispatchEvent(new dom.window.Event('change'));assert.ok($('#ks-detail').textContent.includes('inzwischen geklärt'));
assert.equal(d.querySelectorAll('#ks-components > .record').length,34);assert.deepEqual(errors,[]);assert.ok(!html.includes('fetch(')&&!html.includes('localStorage')&&!html.includes('indexedDB'));
const root=path.resolve(__dirname,'../..'),base='f2bf574c6c6fed3a64ac0073823cd07ac24ee537';const changed=execFileSync('git',['diff',base,'--name-only'],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(Boolean);assert.ok(changed.every(f=>f.startsWith('lab/wissenslandkarte/')));const cs=JSON.parse(fs.readFileSync(path.join(root,'data/geometry.claims.json'))).claims;assert.equal(cs.filter(c=>c.id.startsWith('TH-20261009-')).length,39);
const result={basis:base,claim_selections:selections,derived_navigation:true,missing_unit_preserved:true,resolved_historical_conflict_label:true,component_count:34,page_errors:errors,baseline_tracked_files_unchanged:true,expert_corrections_preserved:39,browser_visual_acceptance:'Not completed: browser launch blocked by environment socket permissions. No screenshots or responsive-layout pass claimed.'};fs.writeFileSync(path.join(__dirname,'validation.json'),JSON.stringify(result,null,2)+'\n');console.log(result);dom.window.close();
